architect:
  - proshin-roman
assets:
  - settings.xml: "proshin-roman/finapi-java-client-secrets#settings.xml"
  - pubring.gpg: "proshin-roman/finapi-java-client-secrets#pubring.gpg"
  - secring.gpg: "proshin-roman/finapi-java-client-secrets#secring.gpg"
docker:
  image: "yegor256/rultor-image"
install: |-
  sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
merge:
  commanders:
  - proshin-roman
  - ccostin93
  script: mvn clean install
  squash: true
release:
  script: |
    echo "Author of the request: ${author}"
    mvn versions:set "-DnewVersion=${tag}" --quiet
    git commit -am "${tag}"
    mvn clean deploy -Pjcabi --settings ../settings.xml
