name: "snapshot"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Snapshot"
    runs-on: "maven:3-jdk-8"

    steps:
      - name: "Build & test"
        run: |
          cd ..
          mvn clean package
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.jar
